name: Update Project on Server

on:
  push:
    branches-ignore: ["Testing", "Production"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Test SSH Connection
        env:
          SSH_USER: ${{ secrets.UPDATE_PROJECT_USER }}
          SSH_IP: ${{ secrets.UPDATE_PROJECT_IP }}
          SSH_PORT: ${{ secrets.UPDATE_PROJECT_PORT }}
        run: ssh $SSH_USER@$SSH_IP -p $SSH_PORT "echo Connection Successful"

      - name: Set up virtual environment
        env:
          SSH_USER: ${{ secrets.UPDATE_PROJECT_USER }}
          SSH_IP: ${{ secrets.UPDATE_PROJECT_IP }}
          SSH_PORT: ${{ secrets.UPDATE_PROJECT_PORT }}
          REMOTE_SCRIPT_PATH: ${{ secrets.UPDATE_PROJECT_FILE_PATH }}
        run: ssh $SSH_USER@$UPDATE_PSSH_IPROJECT_IP -p $SSH_PORT $REMOTE_SCRIPT_PATH