name: Update Project on Server

on:
  push:
    branches-ignore:
      - Testing
      - Production

jobs:
  build:
    runs-on: self-hosted
    env:
      SSH_USER: ${{ secrets.UPDATE_PROJECT_USER }}
      SSH_IP: ${{ secrets.UPDATE_PROJECT_IP }}
      SSH_PORT: ${{ secrets.UPDATE_PROJECT_PORT }}
      REMOTE_SCRIPT_PATH: ${{ secrets.UPDATE_PROJECT_FILE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Test SSH Connection
        run: ssh $SSH_USER@$SSH_IP -p $SSH_PORT "echo Connection Successful"

      - name: Set up virtual environment
        run: ssh $SSH_USER@$SSH_IP -p $SSH_PORT $REMOTE_SCRIPT_PATH