name: Format Code with Black

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install black
      - name: Run black to reformat code
        run: |
          source venv/bin/activate
          black .
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --exit-code || git commit -m "Apply black code formatting"
