name: Push Code Changes Back to PR

on:
  workflow_run:
    workflows: ["Format Code with Black"] 
    types:
      - completed 

jobs:
  push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Push changes back to PR branch
        run: |
          PR_BRANCH="${{ github.event.workflow_run.pull_requests[0].head.ref }}"
          echo "Pushing changes to $PR_BRANCH"
          git push origin "$PR_BRANCH"
