name: Tests run

on:
  push:
    branches: ["New-workflow-test"]

jobs:
  services:
  docker:
    image: docker:19.03.12
    options: --privileged  # Grants Docker access within the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.test_webhook }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
