name: Tests run

on:
  pull_request:
    branches: ["Testing", "Production"]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start the application in the background
        run: |
          python3 app/main.py > app.log 2>&1 &
          echo $! > app_pid.txt
          sleep 5

      - name: Test with pytest
        run: coverage run -m pytest

      - name: Run code coverage
        run: |
          coverage report -m --rcfile=.coveragerc --format=markdown >> $GITHUB_STEP_SUMMARY

          # Report again and fail if under 100%.
          # coverage report --fail-under=90

      - name: Stop the application
        run: kill $(cat app_pid.txt) || echo "App already stopped"

      - name: Store coverage report
        uses: actions/upload-artifact@v4
        with:
          path: |
            app.log
            coverage.xml
        if: ${{ failure() }}
