name: Tests run

on:
  push:
    branches: ["New-workflow-test"]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.test_webhook }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
