name: Tests run

on:
  push:
    branches:
      - "New-workflow-test"  # Trigger the workflow on push to this branch

jobs:
  test:
    runs-on: self-hosted  # Use a self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.test_webhook }}  # Access the secret for Discord webhook
        uses: Ilshidur/action-discord@master  # Use the Discord notification action
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
