name: Tests run

on:
  pull_request:
    branches: ["Testing", "Production"]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start the application in the background
        run: |
          python3 app/main.py > app.log 2>&1 &
          echo $! > app_pid.txt
          sleep 5

      - name: Test with pytest
        run: coverage run -m pytest

      - name: Run code coverage
        run: |
          coverage report -m --rcfile=.coveragerc --format=markdown >> $GITHUB_STEP_SUMMARY

          # Report again and fail if under 100%.
          # coverage report --fail-under=90

      - name: Stop the application
        run: kill $(cat app_pid.txt) || echo "App already stopped"

      - name: Store coverage report
        uses: actions/upload-artifact@v4
        with:
          path: |
            app.log
            coverage.xml
        if: ${{ failure() }}
      - name: Send Discord Notification with PR and Test Results
        env:
          DISCORD_WEBHOOK: ${{ secrets.test_webhook }}  # Use the webhook secret
        run: |
          PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          TEST_STATUS="Tests completed successfully"
          if [[ $(coverage report -m | tail -n 1 | awk '{print $NF}') -lt 90 ]]; then
            TEST_STATUS="Tests failed (coverage < 90%)"
          fi

          MESSAGE="**Pull Request:** [${PR_TITLE}](${PR_URL})\n**Author:** ${PR_AUTHOR}\n**Test Status:** ${TEST_STATUS}"

          curl -X POST -H "Content-Type: application/json" -d '{"content": "'"${MESSAGE}"'"}' $DISCORD_WEBHOOK