name: Python application

on:
  pull_request:
    branches: [ "Testing" , "Production" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Start the application in the background
      run: |
          # Run the Python application inside the api folder in the background
          python3 api/main.py &
          echo $! > app_pid.txt  # Save the process ID (PID) to a file
          sleep 5  # Adjust sleep time if needed to allow the app to start
    - name: Test with pytest
      run: | 
          # python3 -m pytest
          coverage run -m pytest
    - name: Run code coverage
      run: |
        coverage report -m --rcfile=.coveragerc --format=markdown >> $GITHUB_STEP_SUMMARY

        # Report again and fail if under 100%.
        # coverage report --fail-under=90
    - name: Stop the application
      run: |
          # Kill the application using the saved PID
          kill $(cat app_pid.txt)
    - name: Store coverage report
      uses: actions/upload-artifact@v4
      with:
        path: coverage.xml
      if: ${{ failure() }}
