name: Trigger Tests and Format

on:
  push:
    branches:
      - "Testing"
      - "Production"
    # Exclude pushes from github-actions[bot] using an if condition
    paths-ignore:
      - '.github/workflows/*'  # Ignore changes in workflow files, for example.

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: Trigger the main workflow
        run: |
          if [[ "${{ github.actor }}" != "github-actions[bot]" ]]; then
            echo "Triggering main workflow due to push from user"
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"event_type": "push-to-branch"}' \
              https://api.github.com/repos/${{ github.repository }}/dispatches
          else
            echo "Bot push detected, not triggering workflow."
          fi
